[ejs.landing]
updateAvailableTooltip = "Nouvelle version du launcher disponible."
usernamePlaceholder = "Pseudo"
usernameEditButton = "Param√®tres"
settingsTooltip = "Param√®tres"
serverStatus = "Serveur:"
serverStatusPlaceholder = "DOWN"
newsButton = "Articles Hetonia"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Merci de contatcer le staff (Err 001)"
launchDetails = "Lancement du jeu.."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "En recherche d'articles.."
newsErrorFailedSpan = "Erreur lors du chargement des articles (Err 002)"
newsErrorRetryButton = "R√©essayer "
newsErrorNoneSpan = "Aucun article.."

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "Connexion Hetonia"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "Email ou nom d'utilisateur"
loginPasswordError = "* Oblig√©"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://hetonia.fr/user/password/reset"
loginForgotPasswordText = "Mot de passe oubli√© ?"
loginRememberMeText = "Se rappeler de moi"
loginButtonText = "Se connecter"
loginNeedAccountLink = "https://Hetonia.fr/user/register/"
loginNeedAccountText = "Cr√©er un compte."
loginPasswordDisclaimer1 = "Votre mot de passe est envoy√© √† Hetonia et n'est jamais stoqu√©. Toutes vos donn√©es sont trait√©s de fa√ßons s√©curis√©s."
loginPasswordDisclaimer2 = "Hetonia n'est pas affili√© √† Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Connexion"
loginWithMicrosoft = "Se connecter avec un compte <b>Microsoft</b>"
loginWithHetonia = "Se connecter avec un compte <b>Hetonia</b>"
CancelButton = "Annuler"

[ejs.overlay]
accountSelectHeader = "S√©lectionner un compte"
accountSelectConfirm = "S√©lectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Param√®tres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "√Ä propos du Launcher"
navUpdates = "Mise √† jours"
navDone = "Enregistrer"
tabAccountHeaderText = "Param√®tres du compte"
tabAccountHeaderDesc = "G√©rer les comptes du launcher."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+"
hetoniaAccount = "Hetonia"
addMojangAccount = "+"
minecraftTabHeaderText = "Param√®tres Minecraft"
minecraftTabHeaderDesc = "Options relier au lancement du jeu."
gameResolutionTitle = "R√©solution du jeu."
launchFullscreenTitle = "Lancer en plein √©cran."
autoConnectTitle = "Se connecter automatiquement a Hetonia au lancement."
launchDetachedTitle = "Lancer Minecraft d√©tach√© du Launcher."
launchDetachedDesc = "Si Minecraft n'est pas d√©tach√©, fermmer le launcher fermera aussi Minecraft."
tabModsHeaderText = "Param√®tres des Mods"
tabModsHeaderDesc = "Activer ou d√©sactiver des mods."
optionalMods = "Mods param√©trables"
shaderpacks = "Packs de Shaders"
shaderpackDesc = "Activer ou d√©sactiver les shaders"
selectShaderpack = "S√©lectionner le Shaderpack"
tabJavaHeaderText = "Param√®tres Java"
tabJavaHeaderDesc = "G√©rer la configuration java (avanc√©)."
memoryTitle = "M√©moire"
maxRAM = "RAM Maximum"
minRAM = "RAM Minimum"
memoryDesc = "La valeur recommand√© minimum est de 4Go de Ram."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Executable Java"
javaExecSelDialogTitle = "Choisir un executable Java"
javaExecSelButtonText = "Choisir le fichier"
javaExecDesc = "L'executable est valid√© avant le lancement."
javaPathDesc = "Le chemin d'acc√®s doit finir par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Param√®tres additionels de la JVM"
jvmOptsDesc = "Options √† donner √† la JVM au moment du lancement. <em>-Xms</em> and <em>-Xmx</em> Ne doivent pas √™tre inclus."
launcherTabHeaderText = "Options du Launcher"
launcherTabHeaderDesc = "Options li√©es au launcher lui m√™me."
allowPrereleaseTitle = "Autoriser les versions b√™ta."
allowPrereleaseDesc = "Les versions B√™ta peuvent avoir des nouvelles fonctionsqui n'ont pas √©t√© totalement tester.<br>Ce sera toujours le cas avec les versions B√™ta."
dataDirectoryTitle = "Dossier des donn√©es"
selectDataDirectory = "S√©lectionner le dossier des donn√©es"
chooseFolder = "Choisir le dossier"
aboutTabHeaderText = "√Ä propos"
aboutTabHeaderDesc = "Voir les informations et changelogs de la version actuelle."
aboutTitle = "Hetonia"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "Console de d√©boggage"
releaseNotes = "Notes de mise √† jour"
changelog = "Changelog"
noReleaseNotes = "Pas de note de mise √† jour üò≠"
viewReleaseNotes = "Voir les notes de mise √† jour sur GitHub"
launcherUpdatesHeaderText = "Mises √† jour du launcher"
launcherUpdatesHeaderDesc = "T√©l√©charger, installer les mises √† jour du launcher."
checkForUpdates = "V√©rification pour de nouvelles mises √† jour"
whatsNew = "Quelles nouvaut√©es"
updateReleaseNotes = "Notes de mises √† jour"

[ejs.waiting]
waitingText = "En attente de r√©ponse de Microsoft.."

[ejs.welcome]
continueButton = "CONTINUER"


[js.discord]
waiting = "En attente du client.."
state = "Hetonia"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "D√©connexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION.."
success = "CONNECT√â"
tryAgain = "R√©essayer "

[js.login.error]
invalidValue = "* Valeure invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Mauvais identifiants/Mot de passe"
desc = "Si les donn√©es fournis sont correctes, merci de contacter le <a href='https://support.Hetonia.fr/'>support</a>."

[js.landing.launch]
pleaseWait = "Merci de patienter.."
failureTitle = "Erreur lors du lancement"
failureText = "Merci de contacter le <a href='https://support.Hetonia.fr/'>support</a>."
okay = "Okay"

[js.landing.selectedAccount]
noAccountSelected = "Pas de compte s√©lectionner"

[js.landing.selectedServer]
noSelection = "Pas de serveur s√©lectionner"
loading = "Chargement.."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "V√©rification des informations syst√®me.."
noCompatibleJava = "Pas d'instalation Java compatible trouv√©."
installJavaMessage = "Pour rejoindre Hetonia, vous devez avoir une instalation 64-bits de Java {major}. Voulez vous que nous l'installion pour vous?"
installJava = "Installez moi Java !"
installJavaManually = "Je pr√©faire le faire moi m√™me."
javaDownloadPrepare = "Pr√©paratoin de l'instalation de Java.."
javaDownloadFailureTitle = "Erreur lors de l'installation de Java"
javaDownloadFailureText = "Vous pouvez contacter le <a href='https://support.Hetonia.fr/'>support</a>."
javaRequired = "Java est requis <br>pour lancer"
javaRequiredMessage = 'Une installation de Java {major} x64 est requis pour lancer le jeu.'
javaRequiredDismiss = "Je comprends"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Impossible de trouver une version de OpenJDK."
javaDownloadCorruptedError = "Le JDK t√©l√©charg√© est peut √™tre corompus."
extractingJava = "Extraction de Java"
javaInstalled = "Java install√©!"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des infromations serveur.."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger une version de la distribution."
pleaseWait = "Merci de patienter.."
errorDuringLaunchTitle = "Erreur lors du lancement"
seeConsoleForDetails = "Merci de contacter le <a href='https://support.Hetonia.fr/'>support</a>"
validatingFileIntegrity = "V√©rification de l'int√©grit√© des fichiers.."
errorDuringFileVerificationTitle = "Erreur lors de la v√©rification des fichiers"
downloadingFiles = "T√©l√©chargement des fichiers.."
errorDuringFileDownloadTitle = "Erreur lors du t√©l√©chargement des fichiers"
preparingToLaunch = "Pr√©paration du lancement.."
launchingGame = "Lancement du jeu.."
launchWrapperNotDownloaded = "Le fichier principal LaunchWrapper, n'a pas r√©ussit √† ce t√©l√©charger correctement. Le jeu ne peut donc pas se lancer.<br><br>If you have time, please <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">submit an issue</a> and let us know what antivirus software you use. We'll contact them and try to straighten things out."
doneEnjoyServer = "Passez un bon moment !"
checkConsoleForDetails = "Merci de contacter le <a href='https://support.Hetonia.fr/'>support</a>"

[js.landing.news]
checking = "√Ä la recherche d'articles."

[js.landing.discord]
loading = "Chargement du jeu.."
joining = "Voyage dans la galaxie!"
joined = "Explore la galaxies!"

[js.overlay]
dismiss = "Ok"

[js.settings.fileSelectors]
executables = "Executables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Quelque chose c'est mal pass√©..."
errorMessage = "Authentification Microsoft rat√©e, merci de r√©essayer."
okButton = "Ok"

[js.settings.mstfLogout]
errorTitle = "Quelque chose c'est mal pass√©..."
errorMessage = "D√©conexion Microsoft rat√©e, merci de r√©essayer."
okButton = "Ok"

[js.settings.authAccountSelect]
selectButton = "S√©lectionner un compte"
selectedButton = "Compte s√©lectionn√© &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>Ce compte est votre dernier compte."
lastAccountWarningMessage = "Vous devez √™tre connecter pour jouer √† Hetonia.<br><br>Vous √™tes sur de vouloir vous d√©connectere ?"
confirmButton = "Oui, je le veux"
CancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "S√©lectionner ce compte"
selectedAccount = "Compte s√©lectionn√© ‚úì"
logout = "Se d√©connecter"

[js.settings.serverListing]
mainServer = "Serveur Principal"

[js.settings.java]
selectedJava = "S√©lectionner: Java {version} ({vendor})"
invalidSelection = "S√©lection Invalide."
requiresJava = "Java {major} x64 est requis."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "B√™ta"
stableReleaseTitle = "Version Stable"
releaseNotesFailed = "Impossible de charger les notes de la version."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible !"
newPreReleaseTitle = "Nouvelle version b√™ta disponible !"
downloadingButton = "T√©l√©chargement.."
downloadButton = 'T√©l√©charger depuis Github <span style="font-size: 10px;color: gray;text-shadow: none !important;">Veuillez fermer le launcher et lancer le fichier .dmg</span>'
latestVersionTitle = "Vous utilisez la derni√®re version"
checkForUpdatesButton = "V√©rification de mise √† jour"
checkingForUpdatesButton = "V√©rification de mise √† jour.."

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale: Impossible de charger la distribution."
fatalErrorMessage = "Le fichier de distribution est un fichier esentiel qui fourni les informations sur les derniers mods et mise √† jour. Le launcher ne peut pas se lancer sans ce fichier."
closeButton = "Fermer le launcher"

[js.uibinder.validateAccount]
failedMessageTitle = "Impossible de raffraichir la connexion"
failedMessage = "Impossible de raffraichir la connexion pour <strong>{account}</strong>. Merci de s√©lectionner un autre compte ou de vous reconnecter."
failedMessageSelectAnotherAccount = "Impossible de raffraichir la connexion pour <strong>{account}</strong>. Merci de vous reconnecter."
loginButton = "Se connecter"
selectAnotherAccountButton = "S√©lectionner un autre compte."

[js.uicore.autoUpdate]
checkingForUpdateButton = "V√©rification des mise √† jour..."
installNowButton = "Installer maintenant."
checkForUpdatesButton = "V√©rifier les mises √† jour."
